# Empty field value results in 'None' value in Python. 
default: &DEFAULT
  num_epochs: 1000
  batch_size: 256


AE_sound:
  <<: *DEFAULT
  model_name: ae_sound
  data_dir: "mimii_baseline/numpy_dataset_context_predict"
  dataset_class: "MachineSoundDataset"  
  checkpoint_dir: "checkpoints/ae_sound"
  context_embedding_file:
  context_filename: 
  log_dir: 'logs/ae_sound'  
  gpu_vis_dev: '0'
  num_epochs: 100
  batch_size: 256
  lr: 0.0001


AE_sound_all:
  <<: *DEFAULT
  model_name: ae_sound
  data_dir: "mimii_baseline/numpy_dataset_context_predict"
  dataset_class: "MachineSoundDataset"
  checkpoint_dir: "checkpoints/ae_sound_all"
  context_embedding_file:
  context_filename: 
  log_dir: 'logs/ae_sound_all'  
  gpu_vis_dev: '0'
  num_epochs: 100
  batch_size: 256
  lr: 0.0001

AE_sound_FiLM_one_hot:
  <<: *DEFAULT
  model_name: ae_sound_film_one_hot
  context_model_name: mlp_sound_64  
  dataset_class: "MachineSoundDataset"  
  data_dir: "/home/people/12329741/scratch/machine_sound/mimii_baseline/numpy_dataset_context_predict"  
  checkpoint_dir: "checkpoints/ae_sound_film_one_hot"
  context_checkpoint_dir: "checkpoints/mlp_sound_64"
  context_embedding_file: 
  context_filename: "contexts.npy"
  log_dir: 'logs/ae_sound_film_one_hot'  
  gpu_vis_dev: '0'
  num_epochs: 100
  batch_size: 256
  lr: 0.0001

AE_sound_FiLM_embed_64:
  <<: *DEFAULT
  model_name: ae_sound_film_embed
  context_model_name: mlp_sound_64  
  dataset_class: "MachineSoundDataset"  
  data_dir: "/home/people/12329741/scratch/machine_sound/mimii_baseline/numpy_dataset_context_predict"  
  checkpoint_dir: "checkpoints/ae_sound_film_embed_64"
  context_checkpoint_dir: "checkpoints/mlp_sound_64"  
  context_embedding_file: "embeddings/checkpoint_MLP_sound_64_epoch_12.npy" 
  context_filename: "contexts.npy"
  log_dir: 'logs/ae_sound_film_embed_64'  
  gpu_vis_dev: '0'
  num_epochs: 100
  batch_size: 256
  lr: 0.0001

MLP_sound_64:
  <<: *DEFAULT
  model_name: mlp_sound_64
  dataset_class: "MachineSoundDataset"  
  data_dir: "mimii_baseline/numpy_dataset_context_predict"
  checkpoint_dir: "checkpoints/mlp_sound_64"
  context_filename: "contexts.npy"
  log_dir: 'logs/mlp_sound_64'  
  gpu_vis_dev: '0'
  num_epochs: 50
  batch_size: 512
  lr: 0.0001
